# Generated by Django 5.2.15 on 2026-06-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='ویژه/شاخص'),
        ),
    ]
