# Generated by Django 5.2.15 on 2026-06-22 18:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=300, verbose_name='تیتر اصلی')),
                ('subheadline', models.CharField(blank=True, max_length=300, verbose_name='تیتر فرعی')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('cta_text', models.CharField(default='کشف رایحه تو', max_length=100, verbose_name='متن دکمه')),
                ('cta_url', models.CharField(default='/shop', max_length=200, verbose_name='لینک دکمه')),
                ('cta_secondary_text', models.CharField(blank=True, max_length=100, verbose_name='متن دکمه دوم')),
                ('cta_secondary_url', models.CharField(blank=True, max_length=200, verbose_name='لینک دکمه دوم')),
                ('badge_text', models.CharField(blank=True, max_length=100, verbose_name='برچسب بالای تیتر')),
                ('video_webm', models.FileField(blank=True, null=True, upload_to='cms/hero/', verbose_name='ویدیو WebM')),
                ('video_poster', models.ImageField(blank=True, null=True, upload_to='cms/hero/', verbose_name='پوستر ویدیو')),
                ('fallback_image', models.ImageField(blank=True, null=True, upload_to='cms/hero/', verbose_name='تصویر جایگزین')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'بنر صفحه اصلی',
                'verbose_name_plural': 'بنر صفحه اصلی',
            },
        ),
        migrations.CreateModel(
            name='TrustBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('icon', models.CharField(choices=[('shield', 'تضمین اصالت'), ('shipping', 'ارسال سریع'), ('consult', 'مشاوره'), ('payment', 'پرداخت امن'), ('custom', 'سفارشی')], default='shield', max_length=20, verbose_name='آیکون')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='توضیح')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'نشان اعتماد',
                'verbose_name_plural': 'نشان\u200cهای اعتماد',
                'ordering': ['sort_order'],
            },
        ),
    ]
