# Generated by Django 5.2.17 on 2026-08-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_order_by_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='trustbadge',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='ترتیب'),
        ),
    ]
