# Generated by Django 5.2.15 on 2026-06-20 15:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='شماره سفارش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('processing', 'در حال پردازش'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده'), ('refunded', 'مرجوع شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('subtotal', models.PositiveBigIntegerField(verbose_name='جمع جزء')),
                ('discount_amount', models.PositiveBigIntegerField(default=0, verbose_name='تخفیف')),
                ('shipping_cost', models.PositiveBigIntegerField(default=0, verbose_name='هزینه ارسال')),
                ('total', models.PositiveBigIntegerField(verbose_name='مبلغ نهایی')),
                ('coupon_code', models.CharField(blank=True, max_length=50, verbose_name='کد تخفیف')),
                ('free_shipping', models.BooleanField(default=False, verbose_name='ارسال رایگان')),
                ('shipping_name', models.CharField(max_length=200, verbose_name='نام گیرنده')),
                ('shipping_phone', models.CharField(max_length=11, verbose_name='شماره گیرنده')),
                ('shipping_province', models.CharField(max_length=100, verbose_name='استان')),
                ('shipping_city', models.CharField(max_length=100, verbose_name='شهر')),
                ('shipping_address', models.TextField(verbose_name='آدرس')),
                ('shipping_postal_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=300, verbose_name='نام محصول')),
                ('product_price', models.PositiveBigIntegerField(verbose_name='قیمت واحد')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('subtotal', models.PositiveBigIntegerField(verbose_name='جمع')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
    ]
