# Generated by Django 5.2.15 on 2026-06-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='کد رهگیری پست'),
        ),
    ]
