# Generated by Django 5.2.15 on 2026-06-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='کد پستی'),
        ),
    ]
