# Generated by Django 5.2.15 on 2026-08-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_purchase_code_order_shipping_plate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purchase_code',
            field=models.CharField(db_index=True, max_length=6, unique=True, verbose_name='کد خرید'),
        ),
    ]
