# Generated by Django 5.2.15 on 2026-06-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zarinpal_merchant_id', models.CharField(blank=True, max_length=100, verbose_name='کد مرچنت زرین\u200cپال')),
                ('kavenegar_api_key', models.CharField(blank=True, max_length=200, verbose_name='کلید API کاوه\u200cنگار')),
                ('kavenegar_template', models.CharField(blank=True, default='verify', max_length=100, verbose_name='قالب پیامک')),
            ],
            options={
                'verbose_name': 'تنظیمات پایه',
                'verbose_name_plural': 'تنظیمات پایه',
            },
        ),
    ]
