# Generated by Django 5.2.15 on 2026-06-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_storesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='license_holder',
            field=models.CharField(blank=True, max_length=200, verbose_name='صادرکننده مجوز'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='نام انگلیسی'),
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='key',
            field=models.CharField(choices=[('scent', 'رایحه'), ('skin_type', 'نوع پوست'), ('volume', 'حجم'), ('product_type', 'نوع محصول'), ('note_top', 'نت اولیه'), ('note_middle', 'نت میانی'), ('note_base', 'نت پایانی'), ('license', 'مجوز/اصالت')], max_length=50, verbose_name='کلید'),
        ),
    ]
