# Generated by Django 5.2.15 on 2026-06-22 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_license_holder_product_name_en_review_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storesettings',
            name='kavenegar_api_key',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='kavenegar_template',
        ),
    ]
