# Generated by Django 5.2.17 on 2026-08-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_storesettings_contact_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='ترتیب'),
        ),
    ]
