# Generated by Django 5.2.15 on 2026-06-22 21:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_login_enabled', models.BooleanField(default=True, verbose_name='ورود با OTP')),
                ('access_token_lifetime_minutes', models.PositiveSmallIntegerField(default=15, verbose_name='عمر Access Token (دقیقه)')),
                ('refresh_token_lifetime_days', models.PositiveSmallIntegerField(default=7, verbose_name='عمر Refresh Token (روز)')),
                ('rotate_refresh_tokens', models.BooleanField(default=True, verbose_name='چرخش Refresh Token')),
                ('admin_bypass_phone', models.CharField(blank=True, max_length=11, verbose_name='شماره bypass ادمین')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات احراز هویت',
                'verbose_name_plural': 'تنظیمات احراز هویت',
            },
        ),
        migrations.CreateModel(
            name='OtpSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_length', models.PositiveSmallIntegerField(default=6, verbose_name='طول OTP')),
                ('expiry_seconds', models.PositiveIntegerField(default=120, verbose_name='انقضا (ثانیه)')),
                ('max_verify_attempts', models.PositiveSmallIntegerField(default=5, verbose_name='حداکثر تلاش تأیید')),
                ('verify_window_seconds', models.PositiveIntegerField(default=900, verbose_name='پنجره تلاش (ثانیه)')),
                ('rate_limit_count', models.PositiveSmallIntegerField(default=5, verbose_name='محدودیت درخواست')),
                ('rate_limit_window_seconds', models.PositiveIntegerField(default=900, verbose_name='پنجره درخواست (ثانیه)')),
                ('resend_delay_seconds', models.PositiveIntegerField(default=60, verbose_name='تأخیر ارسال مجدد (ثانیه)')),
                ('ip_rate_limit_count', models.PositiveSmallIntegerField(default=20, verbose_name='محدودیت IP')),
                ('ip_rate_limit_window_seconds', models.PositiveIntegerField(default=3600, verbose_name='پنجره IP (ثانیه)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات OTP',
                'verbose_name_plural': 'تنظیمات OTP',
            },
        ),
        migrations.CreateModel(
            name='OtpTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='نام قالب')),
                ('sms_ir_template_id', models.PositiveIntegerField(verbose_name='شناسه قالب SMS.ir')),
                ('parameter_name', models.CharField(default='Code', max_length=50, verbose_name='نام پارامتر')),
                ('body_preview', models.TextField(blank=True, default='کد تایید شما: {Code}', verbose_name='پیش\u200cنمایش متن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قالب OTP',
                'verbose_name_plural': 'قالب\u200cهای OTP',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SmsProviderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_mode', models.CharField(choices=[('mock', 'Mock (توسعه)'), ('smsir', 'SMS.ir')], default='mock', max_length=20, verbose_name='ارائه\u200cدهنده')),
                ('api_key_encrypted', models.TextField(blank=True, verbose_name='کلید API رمزنگاری\u200cشده')),
                ('base_url', models.CharField(default='https://api.sms.ir/v1', max_length=200, verbose_name='Base URL')),
                ('is_sandbox', models.BooleanField(default=True, verbose_name='حالت Sandbox')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('last_test_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین تست')),
                ('last_test_status', models.CharField(choices=[('ok', 'موفق'), ('failed', 'ناموفق'), ('unknown', 'نامشخص')], default='unknown', max_length=20, verbose_name='وضعیت تست')),
                ('last_test_message', models.TextField(blank=True, verbose_name='پیام تست')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات SMS',
                'verbose_name_plural': 'تنظیمات SMS',
            },
        ),
        migrations.CreateModel(
            name='AuthAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('otp_requested', 'درخواست OTP'), ('otp_verified', 'تأیید OTP'), ('otp_failed', 'OTP ناموفق'), ('login_success', 'ورود موفق'), ('login_blocked', 'مسدود شده'), ('token_refreshed', 'تازه\u200cسازی توکن'), ('logout', 'خروج')], db_index=True, max_length=30, verbose_name='عملیات')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=11, verbose_name='شماره')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'لاگ احراز هویت',
                'verbose_name_plural': 'لاگ\u200cهای احراز هویت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OtpRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=11, verbose_name='شماره')),
                ('code_hash', models.CharField(max_length=64, verbose_name='هش کد')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('verified', 'تأیید شده'), ('expired', 'منقضی'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='تلاش\u200cها')),
                ('expires_at', models.DateTimeField(verbose_name='انقضا')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تأیید')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otp_requests', to='accounts.otptemplate')),
            ],
            options={
                'verbose_name': 'درخواست OTP',
                'verbose_name_plural': 'درخواست\u200cهای OTP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=11, verbose_name='شماره')),
                ('message_type', models.CharField(choices=[('otp', 'OTP')], default='otp', max_length=20, verbose_name='نوع')),
                ('provider', models.CharField(max_length=20, verbose_name='ارائه\u200cدهنده')),
                ('status', models.CharField(choices=[('sent', 'ارسال شده'), ('failed', 'ناموفق'), ('simulated', 'شبیه\u200cسازی')], max_length=20, verbose_name='وضعیت')),
                ('request_data', models.JSONField(blank=True, default=dict, verbose_name='درخواست')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='پاسخ')),
                ('provider_message_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه پیام')),
                ('error_message', models.TextField(blank=True, verbose_name='خطا')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.otptemplate')),
            ],
            options={
                'verbose_name': 'لاگ SMS',
                'verbose_name_plural': 'لاگ\u200cهای SMS',
                'ordering': ['-created_at'],
            },
        ),
    ]
