# Generated by Django 5.2.17 on 2026-08-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_otp_sms_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authauditlog',
            name='action',
            field=models.CharField(choices=[('login_success', 'ورود موفق'), ('login_blocked', 'مسدود شده'), ('token_refreshed', 'تازه\u200cسازی توکن'), ('logout', 'خروج')], db_index=True, max_length=30, verbose_name='عملیات'),
        ),
    ]
