# Generated by Django 5.2.15 on 2026-08-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_authsettings_admin_phones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authauditlog',
            name='action',
            field=models.CharField(choices=[('login_success', 'ورود موفق'), ('login_blocked', 'مسدود شده'), ('token_refreshed', 'تازه\u200cسازی توکن'), ('logout', 'خروج'), ('password_changed', 'تغییر رمز عبور')], db_index=True, max_length=30, verbose_name='عملیات'),
        ),
    ]
