# Generated by Django 5.2.15 on 2026-08-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_authauditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authsettings',
            name='refresh_token_lifetime_days',
            field=models.PositiveSmallIntegerField(default=90, verbose_name='عمر Refresh Token (روز)'),
        ),
    ]
