# Generated by Django 5.2.17 on 2026-08-26 21:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_authsettings_refresh_token_lifetime_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='authsettings',
            name='remember_device_default',
            field=models.BooleanField(default=True, verbose_name='تیک «مرا به خاطر بسپار» به\u200cصورت پیش\u200cفرض'),
        ),
        migrations.AddField(
            model_name='authsettings',
            name='trusted_device_lifetime_days',
            field=models.PositiveSmallIntegerField(default=180, help_text='مدتی که «مرا به خاطر بسپار» بدون ورود مجدد کار می\u200cکند.', verbose_name='عمر دستگاه مطمئن (روز)'),
        ),
        migrations.AddField(
            model_name='user',
            name='session_epoch',
            field=models.PositiveIntegerField(default=0, verbose_name='نسل نشست'),
        ),
        migrations.AlterField(
            model_name='authauditlog',
            name='action',
            field=models.CharField(choices=[('login_success', 'ورود موفق'), ('login_blocked', 'مسدود شده'), ('token_refreshed', 'تازه\u200cسازی توکن'), ('logout', 'خروج'), ('password_changed', 'تغییر رمز عبور'), ('device_login', 'ورود خودکار دستگاه'), ('device_trusted', 'ثبت دستگاه مطمئن'), ('device_revoked', 'حذف دستگاه مطمئن'), ('device_reuse', 'استفاده مجدد از توکن دستگاه'), ('sessions_revoked', 'ابطال نشست\u200cها'), ('admin_password_set', 'تغییر رمز توسط ادمین'), ('role_changed', 'تغییر سطح دسترسی')], db_index=True, max_length=30, verbose_name='عملیات'),
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('previous_token_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='نام دستگاه')),
                ('user_agent', models.CharField(blank=True, max_length=400, verbose_name='User-Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('last_used_at', models.DateTimeField(auto_now_add=True, verbose_name='آخرین استفاده')),
                ('expires_at', models.DateTimeField(verbose_name='انقضا')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='ابطال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دستگاه مطمئن',
                'verbose_name_plural': 'دستگاه\u200cهای مطمئن',
                'ordering': ['-last_used_at'],
            },
        ),
    ]
