# Generated by Django 5.2.15 on 2026-06-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('success', 'موفق'), ('failed', 'ناموفق'), ('needs_review', 'نیازمند بررسی'), ('refunded', 'مرجوع')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
    ]
