# Generated by Django 5.2.15 on 2026-06-20 15:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='کد')),
                ('coupon_type', models.CharField(choices=[('percent', 'درصدی'), ('fixed', 'مبلغ ثابت'), ('free_shipping', 'ارسال رایگان')], max_length=20, verbose_name='نوع')),
                ('value', models.PositiveBigIntegerField(help_text='درصد یا مبلغ تومان', verbose_name='مقدار')),
                ('min_order_amount', models.PositiveBigIntegerField(default=0, verbose_name='حداقل خرید')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر استفاده')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده')),
                ('per_user_limit', models.PositiveIntegerField(default=1, verbose_name='محدودیت هر کاربر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='از تاریخ')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='تا تاریخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupons.coupon')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'استفاده از کد تخفیف',
                'verbose_name_plural': 'استفاده\u200cهای کد تخفیف',
            },
        ),
    ]
