# Generated by Django 5.2.15 on 2026-06-22 00:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('orders', '0002_order_tracking_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='couponusage',
            constraint=models.UniqueConstraint(fields=('coupon', 'user', 'order'), name='unique_coupon_usage_per_order'),
        ),
    ]
